#!/bin/bash

echo "🔍 GALLERY TROUBLESHOOTING GUIDE"
echo "=================================="
echo ""
echo "✅ FIXES APPLIED:"
echo "  1. Removed 'completed' status filter from gallery"
echo "  2. Added support for both 'docs' and 'documents' fields"
echo "  3. Added URL extraction for object formats"
echo "  4. Added detailed logging"
echo ""
echo "📋 TESTING STEPS:"
echo ""
echo "1. Open browser and go to: http://localhost:5001/visit-gallery.html"
echo "   (or your frontend URL)"
echo ""
echo "2. Open browser console (F12) and check for:"
echo "   - '📊 Gallery filter:' message"
echo "   - '📸 Found X visits total' message"
echo "   - '🔍 Visit ...' messages showing each visit"
echo "   - '✅ Added photo:' messages for each image"
echo ""
echo "3. Check backend terminal for the same log messages"
echo ""
echo "4. If no images appear:"
echo "   a) Check if any visits have photos uploaded"
echo "   b) Verify the photo URLs in the logs"
echo "   c) Try uploading a new image to a visit"
echo ""
echo "🧪 QUICK DATABASE CHECK:"
echo "To see what's in your database, you can run:"
echo ""
echo "  In MongoDB shell or Compass, run:"
echo "  db.visits.find({}, {photos: 1, videos: 1, docs: 1, status: 1}).pretty()"
echo ""
echo "This will show all visits with their media arrays."
echo ""
echo "🔧 BACKEND LOGS:"
echo "Check your backend terminal for messages like:"
echo "  📊 Gallery filter: {}"
echo "  📸 Found 5 visits total"
echo "  🔍 Visit 123... (scheduled): 3 photos, 0 videos, 0 docs"
echo "  ✅ Added photo: /uploads/photos/abc123.jpg"
echo ""
echo "If you see '📸 Found 0 visits total', you need to:"
echo "  - Create some visits first"
echo "  - Upload images to those visits"
echo ""
echo "=================================="
echo "Backend should have auto-restarted with nodemon."
echo "If not, restart manually: cd backend && npm run dev"
echo "=================================="
